### ISSUE TITLE
ui-gmap-polylines - setVisible: not a boolean

### ISSUE THREAD

**Issue by flc** [angular-ui/angular-google-maps#1435] opened 2015-08-13 03:22 UTC
when using the ui-gmap-polylines directive the visible parameter seem to work if the value comes from a model property however it throws the below errors.

http://plnkr.co/edit/GLO3fZ1eD5LKCqaUZP9Z?p=preview
```
Error: setVisible: not a boolean
sf@http://maps.gstatic.com/maps-api-v3/api/js/19/20/main.js:24:683
tf@http://maps.gstatic.com/maps-api-v3/api/js/19/20/main.js:24:796
ng/<@http://maps.gstatic.com/maps-api-v3/api/js/19/20/main.js:29:1294
i/</<@http://raw.githubusercontent.com/angular-ui/angular-google-maps/2.1.5/dist/angular-google-maps.min.js:6:9072
$RootScopeProvider/this.$get</Scope.prototype.$digest@https://code.angularjs.org/1.4.3/angular.js:15683:23
$RootScopeProvider/this.$get</Scope.prototype.$evalAsync/<@https://code.angularjs.org/1.4.3/angular.js:15885:15
completeOutstandingRequest@https://code.angularjs.org/1.4.3/angular.js:5394:7
Browser/self.defer/timeoutId<@https://code.angularjs.org/1.4.3/angular.js:5666:7

https://code.angularjs.org/1.4.3/angular.js
Line 12330
```

if i change to the latest code I get the following and polylines doesn't show up at all:

```
error within chunking iterator: TypeError: _.get is not a function
https://code.angularjs.org/1.4.3/angular.js
Line 12330
```

also, how is it possible to dynamically hide a certain polyline?
that hidePolyline function doesn't seem to do the job.

**Comment by wrummler** [comment] 2015-08-14 15:24
At some point AGM transitioned from lodash 2 to lodash 3, which I think is why you're seeing the first error. At least I don't see it when I bump your example to use 3.10.1. (Btw, lots of the examples still use lodash 2, and they need updating. Feel free to contribute these updates; most if not all of AGM's active project members are time-strapped volunteers, so we *really* appreciate them (both the updates and the project stalwarts ;-) .)

The `_.get`-related message is because your example is using lodash older than 3.7 (which introduced `_.get`). A recent commit on master that isn't in the released 2.1.5 introduced usage of `_.get` to make specifying model property paths possible.

All that being accounted for, I can reproduce the seeming non-functionality of your `hidePolyline` function. I'm not sure why it doesn't work. I didn't see any related reports briefly searching over past issues.

**Comment by nmccready** [comment] 2015-08-16 20:18
Marking this as a duplicate as this is the lodash problem #1433

**Closed by nmccready** 2015-08-16 20:18 UTC
Labels: needs investigation

**Comment by wrummler** [comment] 2015-08-20 01:25
@nmccready It seems like there's more to this one than just the lodash dep. The `setVisible: not a boolean` error is reproducible even when including the right lodash.

**Comment by nmccready** [comment] 2015-08-20 17:17
Yeah I fixed in the Poygon PR

**Comment by nmccready** [comment] 2015-08-20 17:18
Fixed here https://github.com/angular-ui/angular-google-maps/pull/1441
