### ISSUE TITLE
How can I properly change an editable flag of a polygon?

### ISSUE THREAD

**Issue by illyashevchenko** [angular-ui/angular-google-maps#1730] opened 2016-02-08 15:03 UTC
I try to use 'issue-930-polygons-updates' example and do the following

```
var scope = angular.element($0).scope();
var poly = scope.map.polys[0];
poly.editable = false;
scope.$apply();
```

And got an error:

> angular.js:11413 TypeError: Cannot set property 'model' of undefined
>     at BasePolysParentModel._Class.setChildScope (model-key.js:180)
>     at BasePolysParentModel.setChildScope (model-key.js:5)
>     at Object.fn (base-polys-parent-model.js:231)
>     at Scope.$digest (angular.js:14046)
>     at Scope.$apply (angular.js:14308)
>     at angular.js:16039
>     at completeOutstandingRequest (angular.js:4852)
>     at angular.js:5225

In this code:

```
_Class.prototype.setChildScope = function(keys, childScope, model) {
          var isScopeObj, key, name, newValue;
          for (key in keys) {
            name = keys[key];
            isScopeObj = this.scopeOrModelVal(name, childScope, model, true);
            if ((isScopeObj != null ? isScopeObj.value : void 0) != null) {
              newValue = isScopeObj.value;
              if (newValue !== childScope[name]) {
                childScope[name] = newValue;
              }
            }
          }
          return childScope.model = model;
        };
```

What am I doing wrong? Is there a better way to change poly's properties which I can't find?

**Comment by ahornerr** [comment] 2016-03-02 00:07
Duplicate of #1562 I believe.

**Closed** 2016-03-02 01:40 UTC
Labels: duplicate
