### ISSUE TITLE
searchbox places change not returning location

### ISSUE THREAD

**Issue by tharrington** [angular-ui/angular-google-maps#1739] opened 2016-02-17 00:11 UTC
I had a searchbox working which would get the lat/lng of a result... All the sudden the result from the searchbox has an empty geometry object:

`],
    "adr_address": "1416 Sunset Blvd, Los Angeles, CA 90026-3432, USA",
    "formatted_address": "1416 Sunset Blvd, Los Angeles, CA 90026, USA",
    "geometry": {
      "location": {}
    },
    "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/geocode-71.png",
    "id": "2312ce8c7d55f25b8fae6ad5ab9910936fd7f5e9",
    "name": "1416 Sunset Blvd",`

has something changed with the API?

**Comment by nmccready** [comment] 2016-02-17 00:16
Possible angular 1.5 glitch that wasn't spec'ed enough. Angular 1.5 has been painful thus far.

**Comment by tharrington** [comment] 2016-02-17 00:17
problem exists in the searchbox example as well.

**Comment by tharrington** [comment] 2016-02-17 00:18
im using angular 1.4.7 and     "angular-google-maps": "~2.3.0",

**Comment by nmccready** [comment] 2016-02-17 00:35
I guess checkout the commit history for files relating to searchbox. It has been changed recently due to feature requests.

**Comment by nmccready** [comment] 2016-02-17 00:36
Commits since Jan https://github.com/angular-ui/angular-google-maps/commits/master/src/coffee/directives/api/models/parent/search-box-parent-model.coffee

**Comment by david-meza** [comment] 2016-02-17 02:27
That's strange, but isn't this part of the Google Geocoder response? Wouldn't this be part of the Google Maps Places library? I'm assuming you have something like this:
    
    events: {
      places_changed: function (searchBox) {
        var loc = searchBox.getPlaces()[0].geometry.location;
        // Some Action with the results
      }
    }

It would seem that maybe the Geocoder is having trouble with that particular address.

**Comment by kandizzy** [comment] 2016-02-17 17:11
Very strange, we haven't changed anything that would affect this. The response does come from the Google Places API. It seems that the Google api does not always return a geometry. In the [Place autocomplete](https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete) example they account for this, but not in the [Places search box](https://developers.google.com/maps/documentation/javascript/examples/places-searchbox) example.

**Comment by tharrington** [comment] 2016-02-17 19:13
@david-meza yes, that's exactly what I'm doing. There is no problem with the address.

@kandizzy I have run Google's provided example and the address does in fact return a location with lat/lng

**Comment by tharrington** [comment] 2016-02-17 19:35
I also tried, with no luck, circumventing the angular search box wrapper and doing it with google's raw javascript api:

`uiGmapIsReady.promise(1).then(function(instances) {
    	$log.info('[+] map is ready');
    	var map = $scope.map.control.getGMap();

    	var input = document.getElementById('pac-input');
		  var searchBox = new google.maps.places.SearchBox(input);
		  map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

		  searchBox.addListener('places_changed', function() {
		  	$log.info('[+] places changed');
    		var places = searchBox.getPlaces();
    		$log.info('[+] got places: ' + JSON.stringify(places));
    	});
    });`

potentially this is an issue with the version of google maps the library is pulling in?

**Comment by tharrington** [comment] 2016-02-17 19:37
well look at that, i got it working... I changed to version 3.23 of google maps:

`uiGmapGoogleMapApiProvider.configure({
	      key: 'mykey',
	      v: '3.23', 
	      libraries: 'geometry,places'
	    });`


Do you see this affecting other areas of the library?

**Comment by kandizzy** [comment] 2016-02-17 19:49
I made this plunkr to test it out. Seems to get the lat/long with 3.17.
http://plnkr.co/edit/yjmqO86Ks38d6DFGqhTM?p=preview

**Comment by kandizzy** [comment] 2016-02-19 17:23
i can't reproduce this error, i tried with angular 1.5 too. I'm going to close this, but feel free to reopen if you can reproduce and send a plunkr to demonstrate.

**Closed by kandizzy** 2016-02-19 17:23 UTC
