### ISSUE TITLE
polygons model path isn't working with nested array

### ISSUE THREAD

**Issue by ringerx** [angular-ui/angular-google-maps#1385] opened 2015-07-09 21:15 UTC
when using the polygons directive, if my array of 'latLongs' is nested i get an error
"error within chunking iterator: InvalidValueError: at index 0: not an instance of LatLng". what am i  overlooking here? it works perfectly otherwise.

working code:
```
           <ui-gmap-polygons
                    models="polygonList"
                    idKey="'id'"
                    path="'shape'">
            </ui-gmap-polygons>
```
```
$scope.polygonList = {
          "id": 87537,
          "shape": [
              {"latitude": 40.74299722222219,
                "longitude": -73.98898500000001 },
              {"latitude": 40.74273055555551,
                "longitude": -73.98894944444447 },
              {"latitude": 40.73888055555551,
                "longitude": -73.98975611111115 }
            ] }

breaking code:
           <ui-gmap-polygons
                    models="polygonList"
                    idKey="'id'"
                    path="'shape.latLong'">
            </ui-gmap-polygons>

$scope.polygonList = {
          "id": 87537,
          "shape": {
            "latLong": [
              {"latitude": 40.74299722222219,
                "longitude": -73.98898500000001},
              {"latitude": 40.74273055555551,
                "longitude": -73.98894944444447},
              { "latitude": 40.73888055555551,
                "longitude": -73.98975611111115 }
            ]
          } }
```

**Comment by wrummler** [comment] 2015-07-09 22:37
It's best to include a link to an immediately runnable [MCVE](https://github.com/angular-ui/angular-google-maps/wiki/MCVE) when raising issues like this. Plunker is preferred, but anything you're comfortable with is also fine as long as it demonstrates what you're asking about. Thanks.

**Comment by ringerx** [comment] 2015-07-10 00:31
sorry about that, i forgot the link in my haste.
http://plnkr.co/edit/U0bYaHWOyVbjMJQ7tie0?p=preview

i hope this gives enough context.

**Comment by wrummler** [comment] 2015-07-10 04:17
Thanks for the plunker. I can reproduce what you're describing. It may be an undocumented limitation of the `path` attribute that it won't work with a "property chain" string. I looked around in the source for something where basically `a['b.c']` was happening where instead you'd want `a.b.c`, since that might be the gist of what's going wrong, but I couldn't pin anything down.

I guess the lesson here might be that the value of `path` isn't evaluated against a model in the same way that an Angular expression is evaluated against a scope. (In the latter case, a "property chain" string does work.) Instead, the value of `path` is used in a simple property access (presumably).

Closing for now. If anyone wants to investigate more closely, feel free to follow up and we could reopen this, possibly as a feature request I suppose. The presumed limitation could also be fodder for a documentation update. Contributions are always welcome. Thanks.

**Comment by ringerx** [comment] 2015-07-10 16:59
there seems to be a lot of uncertainty in the actual cause of this. can it be safe to say that the 'path' functionality is extremely limited in its functionality?

**Comment by wrummler** [comment] 2015-07-10 17:57
It might be safe to say such a statement, except that such a statement is correspondingly extremely vague in what it actually means and adds nothing to the information content of anything. It may even provide disinformation to new users who visit this issue, since the `path` attribute behavior demonstrated here has broken no documented promises and is, to the best of my knowledge (which is unfortunately not perfect), identical to the behavior of all other `ui-gmap-*` directives' attributes whose values name model object properties.

Similarly, it is true that there is some uncertainty in at least two people as to the actual cause of this behavior. At least one person has put considerable effort into examining the source code for an explanation. Others are welcome to do so and follow up here, as stated in a previous comment.

I think it's safest to say what is actually currently known by those who are participating on this issue so far. These things have already been said. Others who know more may choose to participate if they have time. To help encourage that participation, I'll reopen this issue and add an applicable tag.

**Comment by nmccready** [comment] 2015-07-13 00:20
Key areas to research.

- [call - convertPathPoints](https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/models/child/base-poly-child-model.coffee#L24)
- [impl - convertPathPoints](https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/utils/gmap-util.coffee#L173-L213) - creates an MvcArray of LatLngs

Lastly once the an gObject is created in base-poly-child-model the array is attempted to be kept un sync with changes.

[call arraySync](https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/models/child/base-poly-child-model.coffee#L32)

[arraySync](https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/utils/array-sync.coffee)

**Comment by nmccready** [comment] 2015-07-13 00:37
Actually I think this is the problem here. https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/utils/model-key.coffee#L97  It is only evaluating the scope key at one depth level. If we used this [lodash-get](https://lodash.com/docs#get) then it would probably work the way you want.

**Comment by ringerx** [comment] 2015-07-13 18:03
thank you for you responses. to be clear my  intention was not to insult or belittle the path attribute. i was simply trying to put it in perspective. but i agree the behavior has not broken any documented promises, and i will try to choose my words differently in the future. thank you for the areas to look deeper into. i'm looking forward to seeing what i can do to find a solution to my problem.

**Comment by wrummler** [comment] 2015-07-14 15:44
Created a PR to use `_.get` at the three locations where scope and model keys are used in `scopeOrModelVal`. The third seems to be crucial, at least for this issue's MCVE.

@ringerx I owe you an apology. I misread your comment not as an insult to the path attribute but as yet another "this sucks" message from a disappointed and possibly resigned user. (For the record, I think there is nothing at all wrong with disappointment; it can drive any project forward, and one should express it constructively whenever possible.) Your words of thanks are appreciated. Likewise, thank you for contributing this issue and for following up.

Reopening w/r/t PR.

**Closed** 2015-07-14 15:54 UTC
Labels: enhancement
