### ISSUE TITLE
Load dynamic google maps

### ISSUE THREAD

**Issue by Criscros** [angular-ui/angular-google-maps#1371] opened 2015-06-25 12:46 UTC
i have an issue i call google maps when DOM is load and  its works but i call other google maps whit button after load dom  but google maps no works and i resize window google works !!

this is my page  http://smis.com.co:9007/admin3/angularjs/#/inicio

		<button onclick="proyectos()"class="btn btn-info">Proyectos</button>
		<button onclick="seguridad()" class="btn btn-info">Segurida</button>
		

		<div id="proyectos" class="portlet light" >
					<h3>Ubicacion De Proyectos </h3>
					<ui-gmap-google-map center='map.center' zoom='map.zoom'>
						<ui-gmap-marker coords="marker.coords" options="marker.options" events="marker.events" idkey="marker.id">
				        </ui-gmap-marker>
					</ui-gmap-google-map>
					
					<div ng-cloak>
				        <ul>
				            <li>coords update ctr: {{coordsUpdates}}</li>
				            <li>dynamic move ctr: {{dynamicMoveCtr}}</li>
				        </ul>
				    </div>	
		</div>

		<div id="seguridad" class="portlet light hidden" >
					<h3>Seguridad</h3>
					<ui-gmap-google-map center='map.center' zoom='map.zoom'>
						<ui-gmap-marker coords="marker.coords" options="marker.options" events="marker.events" idkey="marker.id">
				        </ui-gmap-marker>
					</ui-gmap-google-map>
					
					<div ng-cloak>
				        <ul>
				            <li>coords update ctr: {{coordsUpdates}}</li>
				            <li>dynamic move ctr: {{dynamicMoveCtr}}</li>
				        </ul>
				    </div>	
		</div>

<script>

	function proyectos(){
		$('#seguridad').addClass("hidden");
		$('#proyectos').removeClass('hidden');
	}
	function seguridad(){
		$('#proyectos').addClass('hidden');
		$('#seguridad').removeClass('hidden');

	}

</script>

**Comment by wrummler** [comment] 2015-06-25 13:20
It's best to include a link to an immediately runnable [MCVE](https://github.com/angular-ui/angular-google-maps/wiki/MCVE) when raising issues like this. Plunker is preferred, but anything you're comfortable with is also fine as long as it works. Thanks.

**Comment by cthrax** [comment] 2015-06-25 15:06
You might also look at the suggestion in the last FAQ http://angular-ui.github.io/angular-google-maps/#!/faq "map is only partially rendered".

**Comment by wrummler** [comment] 2015-06-25 15:38
@Criscros Thanks for editing in that link to your application. It's not quite a minimal example and not independently modifiable, but it might be enough for us to help out.

@cthrax 's pointer to the FAQ looks applicable. The map div under the currently hidden portlet seems to get a computed width/height of auto/auto, whereas the non-hidden portlet's map div gets a computed width/height of 1100/300. When rendering occurs on the hidden portlet's map div, the div is basically unsized and so the map reflects that. Try placing an ng-if on each map where the condition is true if and only if that map is being shown. You might have to add some model or flag to your controller to set this up.

**Comment by Criscros** [comment] 2015-06-25 16:38
when i resize a window the gogole map works  the issue no is load ?

**Comment by wrummler** [comment] 2015-06-25 22:27
That's correct. The problem is not that the map isn't loading. The map is definitely loading. (This was never in doubt.)

The problem is that the map is loading into a zero-width, zero-height div *at the time of loading*. Resizing the window causes the map to redraw itself, so the map "works" after you resize the window.

Please use the suggestion above and from the FAQ.

After you've reviewed the FAQ and tried the suggestion, if the problem persists, follow up here with a description and example showing what you have so far. Thanks.

**Comment by Criscros** [comment] 2015-06-26 15:52
i understand but i dont know how make conditional if that map is being shown i appreciate your help

**Comment by nmccready** [comment] 2015-06-26 15:59
Where is your MVCE (plnkr or jsfiddle)?

**Comment by nmccready** [comment] 2015-06-26 15:59
Closing until this is provided.

**Comment by Criscros** [comment] 2015-06-26 17:15
@nmccready  I appreciate your help
http://plnkr.co/edit/KBCGdPCwecJNUU8dYZHg?p=preview

**Comment by wrummler** [comment] 2015-06-27 02:24
@Criscros You're almost there with your example. All you really need to do is (like we've already pointed out) add an ng-if directive onto each map's parent section's div, where each ng-if has an expression (in the same way as all the other directive attributes you're using) that evaluates to true when the map is showing. Since you're using jQuery to show and hide the maps, you can attach two functions to your controller's scope, each one finding its respective map div and querying whether it's hidden or not. You can then use those functions in the ng-if directives.

If any of this is confusing, you really need to read the Angular docs and/or an Angular tutorial. And keep a good JS tutorial/reference handy, too.

[Here's an updated example](http://plnkr.co/edit/6wongxivnfWfnkITl1qz?p=preview) that uses a very similar approach with `ng-switch`. For your particular example, it's a bit simpler this way. It's still the same concept though --- Prevent each map from loading until its div is unhidden and fully sized on the page. I'd recommend taking your original example and figuring out how to use ng-if to solve the same problem. If you can't manage it, keep trying, because it'll be a rough road developing, debugging, and maintaining your app otherwise. Good luck.

**Closed by wrummler** 2015-06-27 02:24 UTC
Labels: question

**Comment by Criscros** [comment] 2015-06-27 03:11
@wrummler  thank you very much from Colombia !!! thaks , thanks :+1: +1:

**Comment by tomrainedotcom** [comment] 2016-01-27 21:16
I have the same problem but I am loading the map in a dialog box (using angular material - md-dialog). When the dialog opens the first time all is fine, the map renders but the second time and any consecutive times the map loads but does not render. 

Any thoughts?

**Comment by faldunate** [comment] 2016-08-12 00:38
I have the same problem with the dialog box, some solution?
