### ISSUE TITLE
infoWindows don't close correctly

### ISSUE THREAD

**Issue by rickginer** [angular-ui/angular-google-maps#1218] opened 2015-03-12 23:56 UTC
I know this issue has come up before in slightly different scenarios, but I think the problem has crept back in to recent tags. When I run using 2.0.12 or 2.0.13 the infoWindows created using the ui-gmap-markers / ui-gmap-windows directives will open one at a time as expected: When clicking on another marker the previous infoWindow is closed and the new one is opened. 

When using 2.0.14 - 2.0.16 the currently open windows do not close when clicking on other markers. Additionally, the close buttons do not work.

I have been unable to confirm if this is also in the 2.1.x branch as infoWindows don't open at all. I'm not sure if this is because of a breaking change/change of syntax/instability of the branch.

**Comment by nmccready** [comment] 2015-03-13 00:04
2.0.16 should work did you make sure you had that version. 2.0.16 was explicitly for that fix.

**Comment by rickginer** [comment] 2015-03-13 00:31
I'm afraid 2.0.16 did not work for me.

**Comment by nmccready** [comment] 2015-03-13 00:53
Please make an example. It might be that show is stricter. If you don't use show it will open and close fine as well.

**Comment by mesge** [comment] 2015-03-15 06:07
Any luck @rickginer ? I'm also seeing this issue.

**Comment by nmccready** [comment] 2015-03-15 17:39
which window directive is the problem. It is working fine for me on windows. Please provide an example to show the problem. That way I can figure out if it is how it is being used or an internal issue.

**Comment by mesge** [comment] 2015-03-16 01:08
In this plunker close doesn't seem to work when directly manipulating show, as well as when you use the close button. I've also included v2.0.12 (commented out) where windows works as expected. I'm not sure if this is an issue caused by how I'm using it in this example or if this is an internal issue. 

I'm on Chrome Version 41.0.2272.89 with OSX.

http://embed.plnkr.co/O8SUM1CVIhknIungc7cd/preview

**Comment by rickginer** [comment] 2015-03-16 02:31
@mesge you seem to be looping through all the markers and setting their visible property to true every time the watch is triggered. Not sure what the watch is supposed to do but if you remove it the close buttons work fine.
@nmccready I have tried with and without the 'show' and see the same thing. I will get a plunkr together as soon as I can, but might be a few days. I hope you are OK to leave this open until then. I really appreciate your help and the dev time you spend on this!

**Comment by nmccready** [comment] 2015-03-16 13:53
closing see the example off 2.0.X lastest.

**Closed by nmccready** 2015-03-16 13:53 UTC
