### ISSUE TITLE
Example in marker page documentation now working

### ISSUE THREAD

**Issue by FrancescoMussi** [angular-ui/angular-google-maps#1518] opened 2015-09-18 08:37 UTC
The demo in the documentation page about markers is empty:

http://angular-ui.github.io/angular-google-maps/#!/api/marker

**Comment by nmccready** [comment] 2015-09-18 14:19
Duplicate of #1495 and known. I have not had time to look into it.

**Closed** 2015-09-18 14:19 UTC
Labels: duplicate
