### ISSUE TITLE
[develop] Markers Directive set different zindex to markers

### ISSUE THREAD

**Issue by barisakpunar** [angular-ui/angular-google-maps#1040] opened 2014-12-24 10:57 UTC
My marker model has zIndex property and it isn't applied when markers are rendered.I'm using markers directive.
So I tried to give different zIndex to different markers by using markersoptions. But I couldn't find a way to get each marker in markersoptions.
Is there a way to get individual marker in markersoptions? 
Or normally when setting the zIndex property in marker model should it work?

**Comment by bii** [comment] 2015-10-09 13:47
Apparently this is still a bug. @nmccready  Can you confirm?
@barisakpunar did you work around it?

**Comment by nmccready** [comment] 2015-10-09 13:49
I don't know please make plnkr.

**Comment by bii** [comment] 2015-10-09 14:19
@nmccready check it out http://plnkr.co/edit/gPOuuDqJfp3ei1EKRMD8

**Comment by bii** [comment] 2015-10-09 14:26
Originally I wanted to set zIndex and couldn't get it to work. Then I tried out the property "visible" and couldn't get it to work either. I have a lot of markers that have have different icons depending on the location type and I want to set different zIndex on them so that one I prioritize show on top.

**Comment by nmccready** [comment] 2015-10-09 15:24
Yeah it appears to be getting stomped, as I see no change from options.

**Comment by nmccready** [comment] 2015-10-09 15:24
The bug probably exists in markerChildModel

**Comment by bii** [comment] 2015-10-10 13:57
Thanks for creating  bug. Is there a work around until fix?

**Comment by nmccready** [comment] 2015-10-12 01:26
Work around woukd be to use control.getPlurals and iterate through all of them and set the index

**Comment by bii** [comment] 2015-10-13 07:32
@nmccready could you elaborate a little bit more?

**Comment by nmccready** [comment] 2015-10-13 13:57
Basically I mean working with all the gObjects which are markers directly to set the zIndex manually. You have access to all gObjects w/ model via the control attribute. Via the [uiGmapPlural](https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/plural.coffee#L17-L18) which is extended to markers [here](https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/markers.coffee#L39-L45).  Not getGMarkers is deprecated.

**Comment by nmccready** [comment] 2015-10-13 14:00
See the docs http://angular-ui.github.io/angular-google-maps/#!/api/markers on control attribute. A child model is a model which has a gObject. So you will get the model paired with the google object along with its scope.

**Comment by bii** [comment] 2015-11-12 12:49
When would be the right time to loop through $scope.map.markers.control.getPlurals().allVals ?

**Comment by nmccready** [comment] 2015-11-12 14:35
Post model updates. You do get the model as well. So you can edit the model and the gObject (Marker) directly if you want.

**Comment by bii** [comment] 2015-11-13 09:22
I tried something like this

```javascript
$scope.prioritiseMarkers = function () {
                $scope.map.markers.control.getPlurals().allVals.forEach(function (val) {
                    var clonedModel = val.clonedModel;
                    var zIndex = clonedModel.options.zIndex;
                    var gObject = val.gObject;
                    gObject.setZIndex(window.google.maps.Marker.MAX_ZINDEX + zIndex);
                });
            }
```
and I added it to map events idle and tilesloaded but it gives an error saying that $scope.map.markers.control.getPlurals is not a function. In events zoom_changed and center_changed it works fine.

**Comment by nmccready** [comment] 2015-11-13 16:07
Yeah that makes sense as the first tilesloaded and idle probably happen before controls.getPlurals is extended. So either do a simple null/undefined function check. The later idles and centers it will be there. Its not that big of a deal.

**Comment by anteriovieira** [comment] 2016-12-26 15:06
Hi @bii , Did you make any progress?

**Comment by anteriovieira** [comment] 2016-12-29 23:06
Hi guys, I tested the directive and found no error. Was just missing the name of the property that identifies the options of each model as described in the [documentation](http://angular-ui.github.io/angular-google-maps/#!/api/markers).

![2016-12-29_20h48_03](https://cloud.githubusercontent.com/assets/1490347/21556517/43132c14-ce08-11e6-83bf-ad5e5f9d8de1.png)

See the code used in the example [here](https://github.com/to-know/issues-angular-google-maps/blob/master/src/issues/1040/issue-controller.js#L11-L13)(controller) and [here](https://github.com/to-know/issues-angular-google-maps/blob/master/src/issues/1040/issue-template.html#L29)(template)

### Models
```js
locationsFiltered = [
	{
		id: 5,
		latitude: 44.4284821,
		longitude: 26.1241451,
		opts: {
			zIndex: 2
		}
	},
	{
		id: 4,
		latitude: 43,
		longitude: 26.1241451,
		opts: {
			zIndex: 1
		}
	},
	// ..
]
```

### Template
```html
<ui-gmap-markers 
    models="locationsFiltered" 
    coords="'self'" 
    icon="'icon'"
    options="'opts'">
</ui-gmap-markers>
```

### Result

![2016-12-29_20h43_44](https://cloud.githubusercontent.com/assets/1490347/21556430/85bdce76-ce07-11e6-8eee-a1d0c9a77caa.png)

**Comment by anteriovieira** [comment] 2016-12-30 01:53
I'm closing this issue by understanding that this is not a bug

**Closed by anteriovieira** 2016-12-30 01:53 UTC
Labels: bug
